<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="RKAINS007" failures="1" tests="8" name="Default test" time="3.239" errors="0" timestamp="2023-07-22T16:03:37 IST">
  <testcase classname="TestPackage.TestTestNG" name="test2" time="0.014"/>
  <testcase classname="TestPackage.TestTestNG" name="test3" time="0.002"/>
  <testcase classname="TestPackage.TestTestNG" name="test6" time="3.023">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestPackage.TestTestNG.test6() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestPackage.TestTestNG.test6() didn't finish within the time-out 3000
at java.base@18.0.2.1/java.lang.Thread.sleep(Native Method)
at app//TestPackage.TestTestNG.test6(TestTestNG.java:48)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d14800.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$MH/0x0000000800d15000.invoke(LambdaForm$MH)
at java.base@18.0.2.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.2.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
at java.base@18.0.2.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base@18.0.2.1/java.lang.reflect.Method.invoke(Method.java:577)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase classname="TestPackage.TestTestNG" name="test1" time="0.005"/>
  <testcase classname="TestPackage.TestTestNG" name="test4" time="0.003"/>
  <testcase classname="TestPackage.TestTestNG" name="test4" time="0.002"/>
  <testcase classname="TestPackage.TestTestNG" name="test4" time="0.003"/>
  <testcase classname="TestPackage.TestTestNG" name="test7" time="0.003"/>
  <testcase classname="TestPackage.TestTestNG" name="test8" time="0.0">
    <ignored/>
  </testcase> <!-- test8 -->
</testsuite> <!-- Default test -->
